### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by AsynchronousAI** [stetre/moonglfw#10]
I am using an x86_64 MacBook Pro, I tried to see if the problem was with dlopen but it wasn't. It happens upon requiring moonglfw.

**Comment by AsynchronousAI** [comment]
I tried to do some tests and this is what I changed luaopen_moonglfx
```c
#include <stdio.h>

LUAMOD_API int luaopen_moonglfw(lua_State *L)
/* Lua calls this function to load the module */
    {
    printf("opening moonglfw\n");
    moonglfw_L = L;

    moonglfw_utils_init(L);

    printf("posting enums and getproc\n");
    lua_newtable(L); /* the glfw table */
    moonglfw_open_enums(L);
    moonglfw_open_getproc(L);
    AddVersions(L);

    /* Do not include hats in glfwGetJoystickButtons() if version >= 3.3.0 */
    printf("glfwInitHint\n");
    if(checkminversion(3, 3, 0))
        glfw.InitHint(GLFW_JOYSTICK_HAT_BUTTONS, GLFW_FALSE);

    if(glfw.Init() != GL_TRUE)
        {
        const char *descr;
        glfw.GetError(&descr);
        if(descr) return luaL_error(L, descr);
        return luaL_error(L, "glfwInit() failed");
        }
    atexit(AtExit);
    glfw.SetErrorCallback(errorCallback);

    /* add glfw functions: */
    printf("adding functions\n");
    luaL_setfuncs(L, Functions, 0);
    printf("adding modules\n");
    moonglfw_open_window(L); printf("window\n");
    moonglfw_open_hint(L); printf("hint\n");
    moonglfw_open_monitor(L); printf("monitor\n");
    moonglfw_open_callbacks(L); printf("callbacks\n");
    moonglfw_open_input(L); printf("input\n"); 
    moonglfw_open_context(L); printf("context\n");
    moonglfw_open_vulkan(L); printf("vulkan\n");
    moonglfw_open_native(L); printf("native\n");

    return 1;
    }
```
It prints everything including "native" so idk where the issue is.

**Comment by AsynchronousAI** [comment]
I did some more debugging this is causing the error:
```c
if(checkminversion(3, 3, 0))
        glfw.InitHint(GLFW_JOYSTICK_HAT_BUTTONS, GLFW_FALSE);

    if(glfw.Init() != GL_TRUE)
        {
        const char *descr;
        glfw.GetError(&descr);
        if(descr) return luaL_error(L, descr);
        return luaL_error(L, "glfwInit() failed");
        }
    atexit(AtExit);
    glfw.SetErrorCallback(errorCallback);
 ```

**Comment by AsynchronousAI** [comment]
I did even more debugging and the error is in `glfw.Init`

**Comment by stetre** [comment]
Is the segmentation fault within the glfw.Init call, or in the error section that follows?

(Unfortunately I don't have a MacOS system so I can't try it myself)

**Comment by AsynchronousAI** [comment]
> Is the segmentation fault within the glfw.Init call, or in the error section that follows?
> 
> (Unfortunately I don't have a MacOS system so I can't try it myself)

I tried recompiling with the error section commented and just a `printf("fail")`. It still created a segmentation fault.

**Comment by stetre** [comment]
Ok, then the segv is likely occurring within glfw.Init, unless for some reason the function pointer itself wasn't loaded properly.

First of all, did the build process go smoothly, with the -DMACOS in place?

**Comment by AsynchronousAI** [comment]
Yes, Building went well without any errors. The glfw.dylib is located in the cwd and I got it from the official website for the correct architecture.

**Comment by AsynchronousAI** [comment]
> unless for some reason the function pointer itself wasn't loaded properly.

This appears to be the error, If I am correct the Init function is in `getproc.c`?

**Comment by stetre** [comment]
The function pointer stored in glfw.Init is loaded in getproc.c at line 95, using the dlsym function (GET macro defined at line 69). dlsym should return either the valid pointer to glfwInit, or NULL on error. The latter case is guarded against, so either dlsym returns garbage (is it likely? I doubt), or the segv is actually within the glfwInit() call.

**Comment by AsynchronousAI** [comment]
I assume the error is with the
```c
GET(Init);
GET(Terminate);
GET(GetVersion);
GET(GetVersionString);
GET(SetErrorCallback);
GET(GetMonitors);
GET(GetPrimaryMonitor);
GET(GetMonitorPos);
GET(GetMonitorPhysicalSize);
GET(GetMonitorName);
GET(SetMonitorCallback);
...
```
section, I know it can `dlopen` without a problem, I tested the error system no problem with that so maybe the problem is with the .dylib file?

**Comment by AsynchronousAI** [comment]
I modified the OPT function to be:
```c
#define GET(fn) do {                                                \
  FP(glfw.fn) = dlsym(Handle, "glfw"#fn);                         \
  if(!glfw.fn) return luaL_error(L, "cannot find glfw"#fn);       \
  else printf("found glfw"#fn"\n"); \
} while(0)
```
It printed everything until `glfwExtensionSupported`, The items afterword probably failed.
***
These are the items that failed:
```c
/* Optional functions, i.e. functions from GLFW > 3.1
* These functions pointers may be NULL, so check before using them.
*/
// GLFW ver 3.2.0:
OPT(GetKeyName);
OPT(GetTimerFrequency);
OPT(GetTimerValue);
OPT(FocusWindow);
OPT(SetWindowAspectRatio);
OPT(SetWindowSizeLimits);
OPT(SetWindowIcon);
OPT(SetWindowMonitor);
OPT(WaitEventsTimeout);
OPT(SetJoystickCallback);
OPT(MaximizeWindow);
// GLFW ver 3.3.0:
OPT(InitHint);
OPT(GetError);
OPT(GetMonitorWorkarea);
OPT(GetMonitorContentScale);
OPT(SetMonitorUserPointer);
OPT(GetMonitorUserPointer);
OPT(WindowHintString);
OPT(GetWindowContentScale);
OPT(GetWindowOpacity);
OPT(SetWindowOpacity);
OPT(RequestWindowAttention);
OPT(SetWindowAttrib);
OPT(SetWindowMaximizeCallback);
OPT(SetWindowContentScaleCallback);
OPT(RawMouseMotionSupported);
OPT(GetKeyScancode);
OPT(GetJoystickHats);
OPT(GetJoystickGUID);
OPT(SetJoystickUserPointer);
OPT(GetJoystickUserPointer);
OPT(JoystickIsGamepad);
OPT(UpdateGamepadMappings);
OPT(GetGamepadName);
OPT(GetGamepadState);
//#ifdef VULKAN requires GLFW version >= 3.20
OPT(GetProcAddress);
OPT(VulkanSupported);
OPT(GetRequiredInstanceExtensions);
OPT(GetInstanceProcAddress);
OPT(GetPhysicalDevicePresentationSupport);
OPT(CreateWindowSurface);
//#endif
/*  Native access functions */
OPT(GetWin32Adapter);
OPT(GetWin32Monitor);
OPT(GetWin32Window);
OPT(GetWGLContext);
//  OPT(GetCocoaMonitor);
//  OPT(GetCocoaWindow);
//  OPT(GetNSGLContext);
OPT(GetX11Display);
OPT(GetX11Adapter);
OPT(GetX11Monitor);
OPT(GetX11Window);
OPT(GetGLXContext);
OPT(GetGLXWindow);
OPT(GetWaylandDisplay);
OPT(GetWaylandMonitor);
OPT(GetWaylandWindow);
OPT(GetMirDisplay);
OPT(GetMirMonitor);
OPT(GetMirWindow);
OPT(GetEGLDisplay);
OPT(GetEGLContext);
OPT(GetEGLSurface);
// GLFW ver 3.3.0:
OPT(SetX11SelectionString);
OPT(GetX11SelectionString);
OPT(GetOSMesaColorBuffer);
OPT(GetOSMesaDepthBuffer);
OPT(GetOSMesaContext);
```

**Comment by AsynchronousAI** [comment]
nvm, I don't think this was the problem, `glfw.Init` in `main.c` is retrieved from the `glfw.dylib`, correct?

**Comment by AsynchronousAI** [comment]
It is not, I checked again `glfw.Init` is the error. That is retrieved from the .dylib file, correct? If so I also tried a Universal version of the `libglfw.dylib` file but the `Segmentation fault: 11` error didn't go away.

**Comment by AsynchronousAI** [comment]
The problem is inside the `glfw.Init` function:
```c
if(glfw.Init)
        printf("GLFW version: %s\n", glfw.GetVersionString());
else
        return luaL_error(L, "failed to load the GLFW library");
```
Outputs `GLFW version: 3.3.8 Cocoa NSGL EGL OSMesa dynamic` and then `Segmentation fault: 11`.

> I added the code above the `glfw.Init` call in `main.c`

**Comment by stetre** [comment]
This just shows that glfw.Init is not NULL, which was already guarded against, but it does not guarantee that it is a meaningful function pointer.

Anyway, this puts the segv out of my reach, unfortunately. What I would do now is to try installing GLFW using brew (as opposed to using the downloaded glfw.dylib), following [these instructions](https://github.com/stetre/moonlibs#installing-on-macos) kindly provided by another MacOS user.

**Comment by AsynchronousAI** [comment]
Thanks for help.
