### ISSUE TITLE
initialisation issue

### ISSUE THREAD

**Issue by awsdert** [stetre/moonglfw#3]
K, so copying over the folders resolved that missing make module error, moogl is now happy, moonglfw on the other hand wouldn't play ball (using the libraries generated by your makefile), I tried commenting out the LUA_PATH & LUA_CPATH overrides but it didn't fix the issue, so far this is all lua or your library reports of the issue:
```
glfwInit() failed
```
Any ideas what could be causing it? (am using official lua lib atm)

**Comment by stetre** [comment]
According to the GLFW manual, [`glfwInit()`](https://www.glfw.org/docs/latest/group__init.html#ga317aac130a235ab08c6db0834907d85e) may fail due to "A bug or configuration error in GLFW, the underlying operating system or its drivers, or a lack of required resources.".

I'd put my bet on "configuration error" but not "in GLFW".

**Comment by stetre** [comment]
To delineate the problem, try executing this simple standalone C program:

    #include <stdio.h>
    #include <GLFW/glfw3.h>
    int main()
        {
        if(glfwInit() != GL_TRUE)
            printf("Initialization failed\n");
        else
            printf("Initialization succeeded\n");
        return 0;
        }

Copy and paste it into a new file called `glfwtest.c` (or whatever you like), then compile and execute it like so:

`$ cc -o glfwtest glfwtest.c -glfw`
`$ ./glfwtest`

**Comment by awsdert** [comment]
alright I'll try when I get home, really want that GUI after all

**Comment by awsdert** [comment]
Got 'Initialization failed', gonna go to bed in a minute so will be late in responding again

**Comment by stetre** [comment]
Fine, this tells you that you can avoid searching for the problem in anything that is not involved in that small C program.

The next thing to do, methink, is to update your graphics drivers, then reinstall GLFW (don't know if this is needed, but just to be sure...), and run the small C program again.

**Comment by awsdert** [comment]
Didn't say I wasn't gonna look for it, just figured you'd respond before I get round to it, additionally I did say I was going to sleep didn't I? So it's only natural to put a problem aside for another day. Anyways I'm gonna look for alternative measures before I do something as drastic as re-installing or changing drivers

**Comment by awsdert** [comment]
Got this "GLFW Error 0x00010008 'Wayland: Failed to connect to display'" after setting the error callback, did a bit of hunting and switched to glfw-x11 and the issue went away on the small code you gave me, gonna try again with my intended project now

**Comment by awsdert** [comment]
Well that sorted that, quick question before I close the issue, how do I change the font size as the text was uber tiny

**Edit:** Never mind wrong project for asking that question, should be in moonnuklear or nuklear

**Comment by stetre** [comment]
You should find this information in the MoonNuklear manual.

I'll improve the error message on `glfwInit()` failure, by the way. Thank you for the feedback.

**Comment by awsdert** [comment]
thx, found the docs, just struggling to change after window creation, created a seprate issue for that here:
https://github.com/stetre/moonnuklear/issues/5
